### ISSUE TITLE
"EnumBadKeyError" unhandled exception with recent changes

### ISSUE THREAD

**Issue by saishivarcr** [vaideesg/omsdk#12]
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_jUcnD8/ansible_module_dellemc_idrac_inventory.py", line 117, in <module>
    main()
  File "/tmp/ansible_jUcnD8/ansible_module_dellemc_idrac_inventory.py", line 85, in main
    from ansible.module_utils.dellemc_idrac import iDRACConnection
  File "/tmp/ansible_jUcnD8/ansible_modlib.zip/ansible/module_utils/dellemc_idrac.py", line 26, in <module>
  File "/usr/lib/python2.7/site-packages/omsdk/sdkcreds.py", line 17, in <module>
    'SNMPv3' : 'SNMPv3'
  File "/usr/lib/python2.7/site-packages/omsdk/sdkcenum.py", line 59, in __init__
    self.enum_type  = Enum(name, EnumWrapper.enum_entries[name])
  File "/usr/lib/python2.7/site-packages/enum.py", line 199, in __init__
    raise EnumBadKeyError(key)
enum.EnumBadKeyError: Enumeration keys must be strings: {'SNMPv1_v2c': 'SNMPv1_v2c', 'User': 'User', 'SNMPv3': 'SNMPv3'}

fatal: [myhost-1]: FAILED! => {
    "changed": false,
    "failed": true,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_jUcnD8/ansible_module_dellemc_idrac_inventory.py\", line 117, in <module>\n    main()\n  File \"/tmp/ansible_jUcnD8/ansible_module_dellemc_idrac_inventory.py\", line 85, in main\n    from ansible.module_utils.dellemc_idrac import iDRACConnection\n  File \"/tmp/ansible_jUcnD8/ansible_modlib.zip/ansible/module_utils/dellemc_idrac.py\", line 26, in <module>\n  File \"/usr/lib/python2.7/site-packages/omsdk/sdkcreds.py\", line 17, in <module>\n    'SNMPv3' : 'SNMPv3'\n  File \"/usr/lib/python2.7/site-packages/omsdk/sdkcenum.py\", line 59, in __init__\n    self.enum_type  = Enum(name, EnumWrapper.enum_entries[name])\n  File \"/usr/lib/python2.7/site-packages/enum.py\", line 199, in __init__\n    raise EnumBadKeyError(key)\nenum.EnumBadKeyError: Enumeration keys must be strings: {'SNMPv1_v2c': 'SNMPv1_v2c', 'User': 'User', 'SNMPv3': 'SNMPv3'}\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 0
}
        to retry, use: --limit @/Dell-EMC-Ansible-Modules-for-iDRAC/main.retry

**Comment by vaideesg** [comment]
Fixed with af62765..60119cb branch.

The OverrideVersionCompatibility variable was not initialized properly.
