### ISSUE TITLE
Import SCP with error when SNMPv3username is none in add_trap_dest

### ISSUE THREAD

**Issue by anupamaloke** [vaideesg/omsdk#13]
If SNMPv3UserName is None, then scp import happens with Error when adding a SNMP trap destination:

    "msg": {
        "ElapsedTimeSinceCompletion": "0", 
        "InstanceID": "JID_048640003432", 
        "JobStartTime": "NA", 
        "JobStatus": "Completed with Errors", 
        "JobUntilTime": "NA", 
        "Message": "Import of system configuration XML file operation completed with errors.", 
        "MessageArguments": "NA", 
        "MessageID": "SYS055", 
        "Name": "Import Configuration", 
        "PercentComplete": "100", 
        "Status": "Success", 
        "file": "\\\\a.b.c.d\\Share\\scpsvtwqi.xml1",  
        "retval": true
    }
 
Following is the corresponding entry in the LC log:
      
      <Operation name="CHANGE">
        <DisplayValue>SNMP V3 Username</DisplayValue>
        <Name>SNMPAlert.3#SNMPv3Username</Name>
        <Detail>
          <OldValue/>
          <NewValue>None</NewValue>
        </Detail>
        <MessageID>Unknown</MessageID>
        <Message>Unknown</Message>
        <Status>Failure</Status>
        <ErrCode>10251</ErrCode>
      </Operation>

**Comment by vaideesg** [comment]
Fixed with Change 037772
