### ISSUE TITLE
enum34 package is causing an error "Dell EMC OMSDK library" required even though OMSDK package is installed

### ISSUE THREAD

**Issue by wilfredm91** [vaideesg/omsdk#26]

**Comment by vaideesg** [comment]
Duplicate of #11. Fixed as part of that checkin

**Comment by vaideesg** [comment]
Duplicate of #11. Fixed as part of that checkin

**Comment by vaideesg** [comment]
Duplicate of #11. Fixed as part of that checkin

**Comment by vaideesg** [comment]
Duplicate of #11. Fixed as part of that checkin

**Comment by vaideesg** [comment]
Duplicate of #11. Fixed as part of that checkin
