### ISSUE TITLE
software inventory

### ISSUE THREAD

**Issue by anupamaloke** [vaideesg/omsdk#5]
idrac.update_mgr.get_swidentity() returns the firmware versions that are both "installed" and "available". Ideally it should only return the installed firmware versions or we should have a flag to control the output

            {
                "BuildNumber": "30", 
                "Classifications": "10", 
                "ComponentID": "25227", 
                "ComponentType": "FRMW", 
                "DeviceID": null, 
                "ElementName": "Integrated Dell Remote Access Controller", 
                "FQDD": "iDRAC.Embedded.1-1", 
                "IdentityInfoType": "OrgID:ComponentType:ComponentID", 
                "IdentityInfoValue": "DCIM:firmware:25227", 
                "InstallationDate": "NA", 
                "InstanceID": "DCIM:PREVIOUS#iDRAC.Embedded.1-1#IDRACinfo", 
                "IsEntity": "true", 
                "MajorVersion": "2", 
                "MinorVersion": "32", 
                "RevisionNumber": "31", 
                "RevisionString": null, 
                "Status": "Available", 
                "SubDeviceID": null, 
                "SubVendorID": null, 
                "Updateable": "true", 
                "VendorID": null, 
                "VersionString": "2.32.31.30", 
                "impactsTPMmeasurements": "false"
            }, 
            {
                "BuildNumber": "40", 
                "Classifications": "10", 
                "ComponentID": "25227", 
                "ComponentType": "FRMW", 
                "DeviceID": null, 
                "ElementName": "Integrated Dell Remote Access Controller", 
                "FQDD": "iDRAC.Embedded.1-1", 
                "IdentityInfoType": "OrgID:ComponentType:ComponentID", 
                "IdentityInfoValue": "DCIM:firmware:25227", 
                "InstallationDate": "2017-06-03T23:05:47Z", 
                "InstanceID": "DCIM:INSTALLED#iDRAC.Embedded.1-1#IDRACinfo", 
                "IsEntity": "true", 
                "MajorVersion": "2", 
                "MinorVersion": "41", 
                "RevisionNumber": "40", 
                "RevisionString": null, 
                "Status": "Installed", 
                "SubDeviceID": null, 
                "SubVendorID": null, 
                "Updateable": "true", 
                "VendorID": null, 
                "VersionString": "2.41.40.40", 
                "impactsTPMmeasurements": "false"
            },

**Comment by vaideesg** [comment]
Fixed in d7ad4c..0b0bc69 

Added a property:
    iDRAC.update_mgr.InstalledFirmware

This returns the list of all firmware that are installed on iDRAC.
